[tool.poetry]
authors = ["Kaidong Hu"]
description = "LLM enhanced game generation"
name =  "techies"
readme = "README.md"
version = "0.0.1"

[tool.poetry.scripts]
techies = "techies.cli:main"

[tool.poetry.dependencies]
python                 =  "3.12.4"

crewai                 =  {extras   =  ["tools"],  version  =  "^0.36.0"}
gpt4all                =  "^2.7.0"
groq                   =  "^0.9.0"
langchain-community    =  "^0.2.6"
langchain-groq         =  "^0.1.6"
langchain-huggingface  =  "^0.0.3"
pyyaml                 =  "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
