name: Sync docs to Wiki

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - new-cli

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clone the Wiki repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs to wiki
        run: |
          rsync -av --delete docs/ wiki/
          cd wiki
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync docs to wiki" || echo "No changes to commit"
          git push
